# Generated by Django 5.2.1 on 2026-07-01 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plataforma", "0002_conversacion_mensaje"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="perfil",
            name="acepto_terminos",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="perfil",
            name="documento_identidad",
            field=models.ImageField(
                blank=True,
                help_text="Documento subido por el usuario para verificación manual.",
                null=True,
                upload_to="identificaciones/",
            ),
        ),
        migrations.AddField(
            model_name="perfil",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="perfil",
            name="suspendido",
            field=models.BooleanField(
                default=False,
                help_text="Cuenta suspendida por un administrador tras un reporte.",
            ),
        ),
        migrations.AddField(
            model_name="perfil",
            name="verificado",
            field=models.BooleanField(
                default=False,
                help_text="Se marca en True solo cuando un administrador revisó y aprobó el documento.",
            ),
        ),
        migrations.CreateModel(
            name="Reporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("acoso", "Acoso o comportamiento inapropiado"),
                            ("suplantacion", "Suplantación de identidad"),
                            ("contenido", "Contenido inapropiado u ofensivo"),
                            ("menor_riesgo", "Sospecha de riesgo hacia un menor"),
                            ("spam", "Spam o cuenta falsa"),
                            ("otro", "Otro motivo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("revisado", models.BooleanField(default=False)),
                (
                    "accion_tomada",
                    models.TextField(
                        blank=True, help_text="Notas del administrador tras revisar."
                    ),
                ),
                (
                    "reportante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_hechos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_reportado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_recibidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Bloqueo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "bloqueado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bloqueos_recibidos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bloqueos_hechos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "bloqueado")},
            },
        ),
    ]
