# Generated by Django 5.2.15 on 2026-07-03 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "plataforma",
            "0003_perfil_acepto_terminos_perfil_documento_identidad_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="grupo",
            name="creador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="grupos_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
